version: '3'

services:
  backend:
    container_name: backend
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 443:443
      - 8000:8000