version: '3'

services:
  backend:
    container_name: backend
    expose:
      - 8000
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    ports:
      - 8000:8000