/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LidarRouteImport } from './routes/_lidar'
import { Route as HailgenRouteImport } from './routes/_hailgen'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as R360RouteImport } from './routes/_360'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LidarLidarIndexRouteImport } from './routes/_lidar/lidar/index'
import { Route as HailgenHailgenIndexRouteImport } from './routes/_hailgen/hailgen/index'
import { Route as R360360IndexRouteImport } from './routes/_360/360/index'
import { Route as HailgenHailgenIdRouteImport } from './routes/_hailgen/hailgen/$id'
import { Route as AuthAuthRegisterRouteImport } from './routes/_auth/auth/register'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth/login'
import { Route as R360360IdRouteImport } from './routes/_360/360/$id'
import { Route as R360IdFrameRouteImport } from './routes/360_/$id/frame'
import { Route as LidarLidarNewIndexRouteImport } from './routes/_lidar/lidar/new/index'
import { Route as LidarLidarIdIndexRouteImport } from './routes/_lidar/lidar/$id/index'
import { Route as HailgenHailgenNewIndexRouteImport } from './routes/_hailgen/hailgen/new/index'
import { Route as R360360NewIndexRouteImport } from './routes/_360/360/new/index'
import { Route as LidarLidarIdLogRouteImport } from './routes/_lidar/lidar/$id/log'
import { Route as LidarLidarNewIdUploadRouteImport } from './routes/_lidar/lidar/new/$id/upload'
import { Route as HailgenHailgenNewIdUploadRouteImport } from './routes/_hailgen/hailgen/new/$id/upload'
import { Route as HailgenHailgenNewIdMaskRouteImport } from './routes/_hailgen/hailgen/new/$id/mask'
import { Route as HailgenHailgenNewIdDepthRouteImport } from './routes/_hailgen/hailgen/new/$id/depth'
import { Route as R360360NewIdPanoramasRouteImport } from './routes/_360/360/new/$id/panoramas'
import { Route as R360360NewIdCapturesRouteImport } from './routes/_360/360/new/$id/captures'

const LidarRoute = LidarRouteImport.update({
  id: '/_lidar',
  getParentRoute: () => rootRouteImport,
} as any)
const HailgenRoute = HailgenRouteImport.update({
  id: '/_hailgen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const R360Route = R360RouteImport.update({
  id: '/_360',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LidarLidarIndexRoute = LidarLidarIndexRouteImport.update({
  id: '/lidar/',
  path: '/lidar/',
  getParentRoute: () => LidarRoute,
} as any)
const HailgenHailgenIndexRoute = HailgenHailgenIndexRouteImport.update({
  id: '/hailgen/',
  path: '/hailgen/',
  getParentRoute: () => HailgenRoute,
} as any)
const R360360IndexRoute = R360360IndexRouteImport.update({
  id: '/360/',
  path: '/360/',
  getParentRoute: () => R360Route,
} as any)
const HailgenHailgenIdRoute = HailgenHailgenIdRouteImport.update({
  id: '/hailgen/$id',
  path: '/hailgen/$id',
  getParentRoute: () => HailgenRoute,
} as any)
const AuthAuthRegisterRoute = AuthAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)
const R360360IdRoute = R360360IdRouteImport.update({
  id: '/360/$id',
  path: '/360/$id',
  getParentRoute: () => R360Route,
} as any)
const R360IdFrameRoute = R360IdFrameRouteImport.update({
  id: '/360_/$id/frame',
  path: '/360/$id/frame',
  getParentRoute: () => rootRouteImport,
} as any)
const LidarLidarNewIndexRoute = LidarLidarNewIndexRouteImport.update({
  id: '/lidar/new/',
  path: '/lidar/new/',
  getParentRoute: () => LidarRoute,
} as any)
const LidarLidarIdIndexRoute = LidarLidarIdIndexRouteImport.update({
  id: '/lidar/$id/',
  path: '/lidar/$id/',
  getParentRoute: () => LidarRoute,
} as any)
const HailgenHailgenNewIndexRoute = HailgenHailgenNewIndexRouteImport.update({
  id: '/hailgen/new/',
  path: '/hailgen/new/',
  getParentRoute: () => HailgenRoute,
} as any)
const R360360NewIndexRoute = R360360NewIndexRouteImport.update({
  id: '/360/new/',
  path: '/360/new/',
  getParentRoute: () => R360Route,
} as any)
const LidarLidarIdLogRoute = LidarLidarIdLogRouteImport.update({
  id: '/lidar/$id/log',
  path: '/lidar/$id/log',
  getParentRoute: () => LidarRoute,
} as any)
const LidarLidarNewIdUploadRoute = LidarLidarNewIdUploadRouteImport.update({
  id: '/lidar/new/$id/upload',
  path: '/lidar/new/$id/upload',
  getParentRoute: () => LidarRoute,
} as any)
const HailgenHailgenNewIdUploadRoute =
  HailgenHailgenNewIdUploadRouteImport.update({
    id: '/hailgen/new/$id/upload',
    path: '/hailgen/new/$id/upload',
    getParentRoute: () => HailgenRoute,
  } as any)
const HailgenHailgenNewIdMaskRoute = HailgenHailgenNewIdMaskRouteImport.update({
  id: '/hailgen/new/$id/mask',
  path: '/hailgen/new/$id/mask',
  getParentRoute: () => HailgenRoute,
} as any)
const HailgenHailgenNewIdDepthRoute =
  HailgenHailgenNewIdDepthRouteImport.update({
    id: '/hailgen/new/$id/depth',
    path: '/hailgen/new/$id/depth',
    getParentRoute: () => HailgenRoute,
  } as any)
const R360360NewIdPanoramasRoute = R360360NewIdPanoramasRouteImport.update({
  id: '/360/new/$id/panoramas',
  path: '/360/new/$id/panoramas',
  getParentRoute: () => R360Route,
} as any)
const R360360NewIdCapturesRoute = R360360NewIdCapturesRouteImport.update({
  id: '/360/new/$id/captures',
  path: '/360/new/$id/captures',
  getParentRoute: () => R360Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/360/$id/frame': typeof R360IdFrameRoute
  '/360/$id': typeof R360360IdRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/hailgen/$id': typeof HailgenHailgenIdRoute
  '/360': typeof R360360IndexRoute
  '/hailgen': typeof HailgenHailgenIndexRoute
  '/lidar': typeof LidarLidarIndexRoute
  '/lidar/$id/log': typeof LidarLidarIdLogRoute
  '/360/new': typeof R360360NewIndexRoute
  '/hailgen/new': typeof HailgenHailgenNewIndexRoute
  '/lidar/$id': typeof LidarLidarIdIndexRoute
  '/lidar/new': typeof LidarLidarNewIndexRoute
  '/360/new/$id/captures': typeof R360360NewIdCapturesRoute
  '/360/new/$id/panoramas': typeof R360360NewIdPanoramasRoute
  '/hailgen/new/$id/depth': typeof HailgenHailgenNewIdDepthRoute
  '/hailgen/new/$id/mask': typeof HailgenHailgenNewIdMaskRoute
  '/hailgen/new/$id/upload': typeof HailgenHailgenNewIdUploadRoute
  '/lidar/new/$id/upload': typeof LidarLidarNewIdUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/360/$id/frame': typeof R360IdFrameRoute
  '/360/$id': typeof R360360IdRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/register': typeof AuthAuthRegisterRoute
  '/hailgen/$id': typeof HailgenHailgenIdRoute
  '/360': typeof R360360IndexRoute
  '/hailgen': typeof HailgenHailgenIndexRoute
  '/lidar': typeof LidarLidarIndexRoute
  '/lidar/$id/log': typeof LidarLidarIdLogRoute
  '/360/new': typeof R360360NewIndexRoute
  '/hailgen/new': typeof HailgenHailgenNewIndexRoute
  '/lidar/$id': typeof LidarLidarIdIndexRoute
  '/lidar/new': typeof LidarLidarNewIndexRoute
  '/360/new/$id/captures': typeof R360360NewIdCapturesRoute
  '/360/new/$id/panoramas': typeof R360360NewIdPanoramasRoute
  '/hailgen/new/$id/depth': typeof HailgenHailgenNewIdDepthRoute
  '/hailgen/new/$id/mask': typeof HailgenHailgenNewIdMaskRoute
  '/hailgen/new/$id/upload': typeof HailgenHailgenNewIdUploadRoute
  '/lidar/new/$id/upload': typeof LidarLidarNewIdUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_360': typeof R360RouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_hailgen': typeof HailgenRouteWithChildren
  '/_lidar': typeof LidarRouteWithChildren
  '/360_/$id/frame': typeof R360IdFrameRoute
  '/_360/360/$id': typeof R360360IdRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/register': typeof AuthAuthRegisterRoute
  '/_hailgen/hailgen/$id': typeof HailgenHailgenIdRoute
  '/_360/360/': typeof R360360IndexRoute
  '/_hailgen/hailgen/': typeof HailgenHailgenIndexRoute
  '/_lidar/lidar/': typeof LidarLidarIndexRoute
  '/_lidar/lidar/$id/log': typeof LidarLidarIdLogRoute
  '/_360/360/new/': typeof R360360NewIndexRoute
  '/_hailgen/hailgen/new/': typeof HailgenHailgenNewIndexRoute
  '/_lidar/lidar/$id/': typeof LidarLidarIdIndexRoute
  '/_lidar/lidar/new/': typeof LidarLidarNewIndexRoute
  '/_360/360/new/$id/captures': typeof R360360NewIdCapturesRoute
  '/_360/360/new/$id/panoramas': typeof R360360NewIdPanoramasRoute
  '/_hailgen/hailgen/new/$id/depth': typeof HailgenHailgenNewIdDepthRoute
  '/_hailgen/hailgen/new/$id/mask': typeof HailgenHailgenNewIdMaskRoute
  '/_hailgen/hailgen/new/$id/upload': typeof HailgenHailgenNewIdUploadRoute
  '/_lidar/lidar/new/$id/upload': typeof LidarLidarNewIdUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/360/$id/frame'
    | '/360/$id'
    | '/auth/login'
    | '/auth/register'
    | '/hailgen/$id'
    | '/360'
    | '/hailgen'
    | '/lidar'
    | '/lidar/$id/log'
    | '/360/new'
    | '/hailgen/new'
    | '/lidar/$id'
    | '/lidar/new'
    | '/360/new/$id/captures'
    | '/360/new/$id/panoramas'
    | '/hailgen/new/$id/depth'
    | '/hailgen/new/$id/mask'
    | '/hailgen/new/$id/upload'
    | '/lidar/new/$id/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/360/$id/frame'
    | '/360/$id'
    | '/auth/login'
    | '/auth/register'
    | '/hailgen/$id'
    | '/360'
    | '/hailgen'
    | '/lidar'
    | '/lidar/$id/log'
    | '/360/new'
    | '/hailgen/new'
    | '/lidar/$id'
    | '/lidar/new'
    | '/360/new/$id/captures'
    | '/360/new/$id/panoramas'
    | '/hailgen/new/$id/depth'
    | '/hailgen/new/$id/mask'
    | '/hailgen/new/$id/upload'
    | '/lidar/new/$id/upload'
  id:
    | '__root__'
    | '/'
    | '/_360'
    | '/_auth'
    | '/_hailgen'
    | '/_lidar'
    | '/360_/$id/frame'
    | '/_360/360/$id'
    | '/_auth/auth/login'
    | '/_auth/auth/register'
    | '/_hailgen/hailgen/$id'
    | '/_360/360/'
    | '/_hailgen/hailgen/'
    | '/_lidar/lidar/'
    | '/_lidar/lidar/$id/log'
    | '/_360/360/new/'
    | '/_hailgen/hailgen/new/'
    | '/_lidar/lidar/$id/'
    | '/_lidar/lidar/new/'
    | '/_360/360/new/$id/captures'
    | '/_360/360/new/$id/panoramas'
    | '/_hailgen/hailgen/new/$id/depth'
    | '/_hailgen/hailgen/new/$id/mask'
    | '/_hailgen/hailgen/new/$id/upload'
    | '/_lidar/lidar/new/$id/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R360Route: typeof R360RouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  HailgenRoute: typeof HailgenRouteWithChildren
  LidarRoute: typeof LidarRouteWithChildren
  R360IdFrameRoute: typeof R360IdFrameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_lidar': {
      id: '/_lidar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LidarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hailgen': {
      id: '/_hailgen'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof HailgenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_360': {
      id: '/_360'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof R360RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lidar/lidar/': {
      id: '/_lidar/lidar/'
      path: '/lidar'
      fullPath: '/lidar'
      preLoaderRoute: typeof LidarLidarIndexRouteImport
      parentRoute: typeof LidarRoute
    }
    '/_hailgen/hailgen/': {
      id: '/_hailgen/hailgen/'
      path: '/hailgen'
      fullPath: '/hailgen'
      preLoaderRoute: typeof HailgenHailgenIndexRouteImport
      parentRoute: typeof HailgenRoute
    }
    '/_360/360/': {
      id: '/_360/360/'
      path: '/360'
      fullPath: '/360'
      preLoaderRoute: typeof R360360IndexRouteImport
      parentRoute: typeof R360Route
    }
    '/_hailgen/hailgen/$id': {
      id: '/_hailgen/hailgen/$id'
      path: '/hailgen/$id'
      fullPath: '/hailgen/$id'
      preLoaderRoute: typeof HailgenHailgenIdRouteImport
      parentRoute: typeof HailgenRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_360/360/$id': {
      id: '/_360/360/$id'
      path: '/360/$id'
      fullPath: '/360/$id'
      preLoaderRoute: typeof R360360IdRouteImport
      parentRoute: typeof R360Route
    }
    '/360_/$id/frame': {
      id: '/360_/$id/frame'
      path: '/360/$id/frame'
      fullPath: '/360/$id/frame'
      preLoaderRoute: typeof R360IdFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_lidar/lidar/new/': {
      id: '/_lidar/lidar/new/'
      path: '/lidar/new'
      fullPath: '/lidar/new'
      preLoaderRoute: typeof LidarLidarNewIndexRouteImport
      parentRoute: typeof LidarRoute
    }
    '/_lidar/lidar/$id/': {
      id: '/_lidar/lidar/$id/'
      path: '/lidar/$id'
      fullPath: '/lidar/$id'
      preLoaderRoute: typeof LidarLidarIdIndexRouteImport
      parentRoute: typeof LidarRoute
    }
    '/_hailgen/hailgen/new/': {
      id: '/_hailgen/hailgen/new/'
      path: '/hailgen/new'
      fullPath: '/hailgen/new'
      preLoaderRoute: typeof HailgenHailgenNewIndexRouteImport
      parentRoute: typeof HailgenRoute
    }
    '/_360/360/new/': {
      id: '/_360/360/new/'
      path: '/360/new'
      fullPath: '/360/new'
      preLoaderRoute: typeof R360360NewIndexRouteImport
      parentRoute: typeof R360Route
    }
    '/_lidar/lidar/$id/log': {
      id: '/_lidar/lidar/$id/log'
      path: '/lidar/$id/log'
      fullPath: '/lidar/$id/log'
      preLoaderRoute: typeof LidarLidarIdLogRouteImport
      parentRoute: typeof LidarRoute
    }
    '/_lidar/lidar/new/$id/upload': {
      id: '/_lidar/lidar/new/$id/upload'
      path: '/lidar/new/$id/upload'
      fullPath: '/lidar/new/$id/upload'
      preLoaderRoute: typeof LidarLidarNewIdUploadRouteImport
      parentRoute: typeof LidarRoute
    }
    '/_hailgen/hailgen/new/$id/upload': {
      id: '/_hailgen/hailgen/new/$id/upload'
      path: '/hailgen/new/$id/upload'
      fullPath: '/hailgen/new/$id/upload'
      preLoaderRoute: typeof HailgenHailgenNewIdUploadRouteImport
      parentRoute: typeof HailgenRoute
    }
    '/_hailgen/hailgen/new/$id/mask': {
      id: '/_hailgen/hailgen/new/$id/mask'
      path: '/hailgen/new/$id/mask'
      fullPath: '/hailgen/new/$id/mask'
      preLoaderRoute: typeof HailgenHailgenNewIdMaskRouteImport
      parentRoute: typeof HailgenRoute
    }
    '/_hailgen/hailgen/new/$id/depth': {
      id: '/_hailgen/hailgen/new/$id/depth'
      path: '/hailgen/new/$id/depth'
      fullPath: '/hailgen/new/$id/depth'
      preLoaderRoute: typeof HailgenHailgenNewIdDepthRouteImport
      parentRoute: typeof HailgenRoute
    }
    '/_360/360/new/$id/panoramas': {
      id: '/_360/360/new/$id/panoramas'
      path: '/360/new/$id/panoramas'
      fullPath: '/360/new/$id/panoramas'
      preLoaderRoute: typeof R360360NewIdPanoramasRouteImport
      parentRoute: typeof R360Route
    }
    '/_360/360/new/$id/captures': {
      id: '/_360/360/new/$id/captures'
      path: '/360/new/$id/captures'
      fullPath: '/360/new/$id/captures'
      preLoaderRoute: typeof R360360NewIdCapturesRouteImport
      parentRoute: typeof R360Route
    }
  }
}

interface R360RouteChildren {
  R360360IdRoute: typeof R360360IdRoute
  R360360IndexRoute: typeof R360360IndexRoute
  R360360NewIndexRoute: typeof R360360NewIndexRoute
  R360360NewIdCapturesRoute: typeof R360360NewIdCapturesRoute
  R360360NewIdPanoramasRoute: typeof R360360NewIdPanoramasRoute
}

const R360RouteChildren: R360RouteChildren = {
  R360360IdRoute: R360360IdRoute,
  R360360IndexRoute: R360360IndexRoute,
  R360360NewIndexRoute: R360360NewIndexRoute,
  R360360NewIdCapturesRoute: R360360NewIdCapturesRoute,
  R360360NewIdPanoramasRoute: R360360NewIdPanoramasRoute,
}

const R360RouteWithChildren = R360Route._addFileChildren(R360RouteChildren)

interface AuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRegisterRoute: typeof AuthAuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRegisterRoute: AuthAuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HailgenRouteChildren {
  HailgenHailgenIdRoute: typeof HailgenHailgenIdRoute
  HailgenHailgenIndexRoute: typeof HailgenHailgenIndexRoute
  HailgenHailgenNewIndexRoute: typeof HailgenHailgenNewIndexRoute
  HailgenHailgenNewIdDepthRoute: typeof HailgenHailgenNewIdDepthRoute
  HailgenHailgenNewIdMaskRoute: typeof HailgenHailgenNewIdMaskRoute
  HailgenHailgenNewIdUploadRoute: typeof HailgenHailgenNewIdUploadRoute
}

const HailgenRouteChildren: HailgenRouteChildren = {
  HailgenHailgenIdRoute: HailgenHailgenIdRoute,
  HailgenHailgenIndexRoute: HailgenHailgenIndexRoute,
  HailgenHailgenNewIndexRoute: HailgenHailgenNewIndexRoute,
  HailgenHailgenNewIdDepthRoute: HailgenHailgenNewIdDepthRoute,
  HailgenHailgenNewIdMaskRoute: HailgenHailgenNewIdMaskRoute,
  HailgenHailgenNewIdUploadRoute: HailgenHailgenNewIdUploadRoute,
}

const HailgenRouteWithChildren =
  HailgenRoute._addFileChildren(HailgenRouteChildren)

interface LidarRouteChildren {
  LidarLidarIndexRoute: typeof LidarLidarIndexRoute
  LidarLidarIdLogRoute: typeof LidarLidarIdLogRoute
  LidarLidarIdIndexRoute: typeof LidarLidarIdIndexRoute
  LidarLidarNewIndexRoute: typeof LidarLidarNewIndexRoute
  LidarLidarNewIdUploadRoute: typeof LidarLidarNewIdUploadRoute
}

const LidarRouteChildren: LidarRouteChildren = {
  LidarLidarIndexRoute: LidarLidarIndexRoute,
  LidarLidarIdLogRoute: LidarLidarIdLogRoute,
  LidarLidarIdIndexRoute: LidarLidarIdIndexRoute,
  LidarLidarNewIndexRoute: LidarLidarNewIndexRoute,
  LidarLidarNewIdUploadRoute: LidarLidarNewIdUploadRoute,
}

const LidarRouteWithChildren = LidarRoute._addFileChildren(LidarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R360Route: R360RouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  HailgenRoute: HailgenRouteWithChildren,
  LidarRoute: LidarRouteWithChildren,
  R360IdFrameRoute: R360IdFrameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
